add developer guide and cleanup docs
haveno-dex/haveno pull request #148
Opened 2021-10-29 19:30 UTC by woodser

2021-10-30 09:21 UTC, erciccione requested changes

2021-10-30 09:21 UTC, erciccione commented on README.md
> +See the [developer guide](./docs/developer-guide.md) to get started developing for Haveno. At this stage, we're mostly looking for help building the backend and APIs.
```suggestion
See the [developer guide](docs/developer-guide.md) to get started developing for Haveno. At this stage, we're mostly looking for help building the backend and APIs.
```

To make it consistent with the other links.

2021-10-30 09:21 UTC, erciccione commented on docs/developer-guide.md
> +14. Advance to finish importing haveno-ui-poc project.
Better move this section to a dedicated document. We already have a dedicated intelliJ doc; adding a guide for another IDE inside another document would be inconsistent. Furthermore, This is not something all devs will need, but only the users of this specific IDE.

A good solution could be to have a dedicated file for instructions for IDEs and move the content of `idea-import.md` there.

2021-10-30 09:21 UTC, erciccione commented on docs/developer-guide.md
> +For documentation on the trade protocol, see [trade protocol](./trade_protocol/trade-protocol.pdf).
Note that github doesn't support showing PDFs, might make sense to link to the markdown file instead.

```suggestion
For documentation on the trade protocol, see [trade protocol](trade_protocol/trade-protocol.pdf).
```

2021-10-30 09:21 UTC, erciccione commented on docs/CONTRIBUTING.md
> +See the [developer guide](developer-guide.md) to get started developing for Haveno.
```suggestion
See the [developer guide](developer-guide.md) to get started developing Haveno.
```

2021-10-30 12:55 UTC, erciccione reviewed
https://github.com/haveno-dex/haveno/blob/master/docs/README.md needs to be updated as well, but i would be more inclined for removing it. It's just another file to maintain.

2021-10-30 12:55 UTC, erciccione commented on docs/import-haveno.md
> +    1. `cd ~/git/`
I would remove this step entirely. We can assume the dev will have their own environment set up where they will clone the two repositories.

2021-10-30 13:35 UTC, woodser commented on docs/developer-guide.md
> +14. Advance to finish importing haveno-ui-poc project.
Done.

2021-10-31 08:23 UTC, erciccione approved these changes

2021-10-31 12:46 UTC, merged