allow getMarketPrice for crypto currencies
haveno-dex/haveno pull request #165
Opened 2021-11-17 14:50 UTC by premek

this makes the 'Can get market prices' API test pass

The api works for crypto currencies too but the price is inverted, e.g. for BTC it returns 250 (1 BTC = 250 XMR), for USD it returns 242 (1 XMR = 242 USD), maybe we should fix that?

2021-11-17 16:00 UTC, woodser commented
Yeah I noticed there was some jankiness in how the price request was handled, something to do with 2 requests stepping on each other.

As implemented, these errors are logged to Alice's console:

```
Nov-17 10:54:59.855 [BisqDaemonMain] WARN  b.c.p.price.PriceFeedService: Exception at applyPriceToConsumer for currency USD. priceProvider=https://price.bisq.wiz.biz/. Exception=java.lang.IllegalStateException: Stream is already completed, no further calls are allowed 
Nov-17 10:54:59.855 [BisqDaemonMain] WARN  bisq.core.api.CorePriceService: Exception at applyPriceToConsumer for currency USD. priceProvider=https://price.bisq.wiz.biz/. Exception=java.lang.IllegalStateException: Stream is already completed, no further calls are allowed bisq.core.provider.price.PriceRequestException: Exception at applyPriceToConsumer for currency USD. priceProvider=https://price.bisq.wiz.biz/. Exception=java.lang.IllegalStateException: Stream is already completed, no further calls are allowed
	at bisq.core.provider.price.PriceFeedService.applyPriceToConsumer(PriceFeedService.java:375)
	at bisq.core.provider.price.PriceFeedService.lambda$request$0(PriceFeedService.java:172)
	at bisq.core.provider.price.PriceFeedService$1.lambda$onSuccess$0(PriceFeedService.java:405)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

I struggled to address this, eventually [reverting my PR](https://github.com/haveno-dex/haveno/commit/4d81d98e00a20756a532c3db045aa1d17fe8a674) after noticing errors.

2021-11-17 16:01 UTC, woodser requested changes
See my comment: https://github.com/haveno-dex/haveno/pull/165#issuecomment-971719748

2021-11-17 22:32 UTC, premek commented
Thanks, i missed that error. I changed the CorePriceService (that seems to be used only from grpc api calls) so it doesn't use the problematic method on the priceFeedService and instead uses cached values. Cache is refreshed from here if it is older than 2 (?) minutes. 
The PriceFeedService obtained through injection should be always the same instance

2021-11-18 00:20 UTC, woodser commented on core/src/main/java/bisq/core/api/CorePriceService.java
> +        if (System.currentTimeMillis() - priceFeedService.getLastRequestTimeStamp().getTime() > TimeUnit.MINUTES.toMillis(2)) {
If I understand right, the API can serve a stale price for almost 2 minutes with this change. Also this approach merely avoids making a simultaneous request at the API level, whereas solving the underlying issue is preferred.

2021-11-18 10:48 UTC, premek commented
We could remove the if and fetch the price every time. I just thought it's
not necessary. It downloads all currencies every time and stores them in
the cache.

I also don't know how often the price node updates the price, it wouldn't
make sense to ask more often than that.

Should we make it 30s for example? Or fetch it every time?

Why I did it like this is because it looks like the original method was
made to support something like you set your currency in the desktop gui
combo box or something to be USD for example and then you see all the
prices in the gui in USD. That's why you used setcurrency and then fetched
the prices separately. It was probably not meant to support concurrent
fetch of different currencies.

I could also try to "fix" the underlying service but it's used on a few
places in the desktop gui

On Thu, 18 Nov 2021, 01:20 woodser, ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In core/src/main/java/bisq/core/api/CorePriceService.java
> <https://github.com/haveno-dex/haveno/pull/165#discussion_r751786037>:
>
> >          if (!priceFeedService.hasPrices())
>              throw new IllegalStateException("price feed service has no prices");
>
> -        try {
> -            priceFeedService.setCurrencyCode(upperCaseCurrencyCode);
> -        } catch (Throwable throwable) {
> -            log.warn("Could not set currency code in PriceFeedService", throwable);
> +        // fetch fresh prices if the cache is older than 2 minutes
> +        if (System.currentTimeMillis() - priceFeedService.getLastRequestTimeStamp().getTime() > TimeUnit.MINUTES.toMillis(2)) {
>
> If I understand right, the API can serve a stale price for almost 2
> minutes with this change. Also this approach merely avoids making a
> simultaneous request at the API level, whereas solving the underlying issue
> is preferred.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/haveno-dex/haveno/pull/165#pullrequestreview-809324181>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAIXUEJBILPCSS3FVYICI23UMRBGVANCNFSM5IHGCAKA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-18 13:18 UTC, woodser commented
> it wouldn't make sense to ask more often than that.

If price data updates 1 second after we refresh the cache, we would serve stale data until the next time we refresh the cache. I don't want to introduce our own lag to refresh price data, so we would want some way to avoid that.

This issue to fetch a price for a currency code is actually a small subset of this other issue to fetch all market prices, which is assigned to you: https://github.com/haveno-dex/haveno/issues/139

Maybe it makes most sense to implement that other call and then use it to power this call with a specific currency code.

2021-11-19 22:06 UTC, premek commented
closing this, will do this as part of #139

2021-11-19 22:06 UTC, closed without merging