Fix pricenode/docker
haveno-dex/haveno pull request #273
Opened 2022-03-15 19:04 UTC by devhyper

Resolves #252 
Updates the pricenode docker for haveno.

2022-03-16 13:56 UTC, erciccione commented
Thanks @devhyper! This is very appreciated. I will review this PR in the next days :)

2022-03-19 09:48 UTC, erciccione requested changes
I found only two minor issues, but I'm thinking would probably be good to link to the main 'pricenode' readme from here, so that people know where to find the commands to test their newly launched pricenode.

2022-03-19 09:48 UTC, erciccione commented on pricenode/docker/README.md
> +Check the logs: `docker compose logs`
`docker-compose logs` was correct

2022-03-19 09:48 UTC, erciccione commented on pricenode/docker/README.md
> +Check the tor hostname: `docker exec docker-pricenode-1 cat /var/lib/tor/pricenode/hostname`
```suggestion
Check the tor hostname: `docker exec docker_pricenode_1 cat /var/lib/tor/pricenode/hostname`
```

2022-03-20 07:27 UTC, erciccione approved these changes
Looks good! Thanks :)

2022-04-03 16:18 UTC, merged

2022-04-03 16:19 UTC, woodser commented
Thank you!